### ISSUE TITLE
[CK][Performance Bug][Urgent]App is slow when entering GMP data

### ISSUE THREAD

**Issue by nubrapika** [avniproject/calcutta-kids#8] opened 2019-08-30 11:36 UTC
See: https://openchs.freshdesk.com/a/tickets/407

status - Still not fixed.

**Comment by sidsamanvay** [comment] 2019-09-12 06:08
Notes:
- The slowness is caused by continuous usage of the app. Not by the amount of data in the device.
- To reproduce the slowness I needed to fill atleast 50 encounters. It is not feasible to do it manually. So I tried to automate with the help of some library. Getting the library workng was not successfull. So have to try manually. Filling 50 new Encounters may not be required. Just opening multiple individual/enrolment/encounters and saving them may reproduce the bug.

**Comment by sidsamanvay** [comment] 2019-09-12 06:09
Moved back to ready, as I am picking up some other card on priority.

**Comment by garimadosar5** [comment] 2021-01-28 08:06
marking it as closed as ticket is marked as resolved

**Closed by garimadosar5** 2021-01-28 08:06 UTC
Labels: bug
